/**
 * sids.h — SID assignments for CORECONF modules
 *
 * AUTO-GENERATED FILE. Do not edit by hand.
 *
 * Generated by: tools/generate_sids_header.py
 * Source SID files:
 *   - sid/ietf-system.sid (downloaded from core-wg/yang-cbor)
 *
 * Note: ietf-interfaces constants are kept as fixed values until
 * an official ietf-interfaces SID file is added under sid/.
 */

#ifndef SIDS_H
#define SIDS_H

/* module: ietf-interfaces (RFC 8343) */
#define SID_IETF_INTERFACES_MODULE          1500
#define SID_IF_INTERFACE                    1533
#define SID_IF_DESCRIPTION                  1534
#define SID_IF_ENABLED                      1535
#define SID_IF_NAME                         1537
#define SID_IF_TYPE                         1538
#define SID_IF_OPER_STATUS                  1544
#define SID_IF_IDENTITY_ETHERNET_CSMACD    1880

#define DELTA_IF_DESCRIPTION    (SID_IF_DESCRIPTION  - SID_IF_INTERFACE)
#define DELTA_IF_ENABLED        (SID_IF_ENABLED      - SID_IF_INTERFACE)
#define DELTA_IF_NAME           (SID_IF_NAME         - SID_IF_INTERFACE)
#define DELTA_IF_TYPE           (SID_IF_TYPE         - SID_IF_INTERFACE)
#define DELTA_IF_OPER_STATUS    (SID_IF_OPER_STATUS  - SID_IF_INTERFACE)

/* module: ietf-system (RFC 7317) — from sid/ietf-system.sid */
#define SID_IETF_SYSTEM_MODULE              1700
#define SID_SYS_CLOCK                       1721
#define SID_SYS_CLOCK_BOOT_DATETIME         1722
#define SID_SYS_CLOCK_CURRENT_DATETIME      1723
#define SID_SYS_NTP_ENABLED                 1755
#define SID_SYS_NTP_SERVER                  1756
#define SID_SYS_NTP_SERVER_NAME             1759
#define SID_SYS_NTP_SERVER_PREFER           1760
#define SID_SYS_NTP_SERVER_UDP              1761
#define SID_SYS_NTP_SERVER_UDP_ADDRESS      1762

#define DELTA_CLOCK_BOOT_DATETIME    (SID_SYS_CLOCK_BOOT_DATETIME    - SID_SYS_CLOCK)
#define DELTA_CLOCK_CURRENT_DATETIME (SID_SYS_CLOCK_CURRENT_DATETIME - SID_SYS_CLOCK)

#define DELTA_NTP_SERVER_NAME    (SID_SYS_NTP_SERVER_NAME    - SID_SYS_NTP_SERVER)
#define DELTA_NTP_SERVER_PREFER  (SID_SYS_NTP_SERVER_PREFER  - SID_SYS_NTP_SERVER)
#define DELTA_NTP_SERVER_UDP     (SID_SYS_NTP_SERVER_UDP     - SID_SYS_NTP_SERVER)
#define DELTA_NTP_UDP_ADDRESS    (SID_SYS_NTP_SERVER_UDP_ADDRESS - SID_SYS_NTP_SERVER_UDP)

#endif /* SIDS_H */
