#!/usr/bin/env python3
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SID_DIR = ROOT / "sid"
OUT_H = ROOT / "include" / "sids.h"

IETF_SYSTEM_SID = SID_DIR / "ietf-system.sid"


def load_sid_map(path: Path) -> dict[str, int]:
    data = json.loads(path.read_text(encoding="utf-8"))
    sid_file = data.get("ietf-sid-file:sid-file", {})
    items = sid_file.get("item", [])
    out = {}
    for item in items:
        ident = item.get("identifier")
        sid = item.get("sid")
        if ident is None or sid is None:
            continue
        out[str(ident)] = int(sid)
    return out


def generate() -> str:
    if not IETF_SYSTEM_SID.exists():
        raise FileNotFoundError(f"Missing SID source file: {IETF_SYSTEM_SID}")

    sys_map = load_sid_map(IETF_SYSTEM_SID)

    sid_sys_module = sys_map["ietf-system"]
    sid_sys_clock = sys_map["/ietf-system:system-state/clock"]
    sid_sys_clock_boot = sys_map["/ietf-system:system-state/clock/boot-datetime"]
    sid_sys_clock_current = sys_map["/ietf-system:system-state/clock/current-datetime"]
    sid_sys_ntp_enabled = sys_map["/ietf-system:system/ntp/enabled"]
    sid_sys_ntp_server = sys_map["/ietf-system:system/ntp/server"]
    sid_sys_ntp_server_name = sys_map["/ietf-system:system/ntp/server/name"]
    sid_sys_ntp_server_prefer = sys_map["/ietf-system:system/ntp/server/prefer"]
    sid_sys_ntp_server_udp = sys_map["/ietf-system:system/ntp/server/udp"]
    sid_sys_ntp_server_udp_address = sys_map["/ietf-system:system/ntp/server/udp/address"]

    lines: list[str] = []
    lines.append("/**")
    lines.append(" * sids.h — SID assignments for CORECONF modules")
    lines.append(" *")
    lines.append(" * AUTO-GENERATED FILE. Do not edit by hand.")
    lines.append(" *")
    lines.append(" * Generated by: tools/generate_sids_header.py")
    lines.append(" * Source SID files:")
    lines.append(" *   - sid/ietf-system.sid (downloaded from core-wg/yang-cbor)")
    lines.append(" *")
    lines.append(" * Note: ietf-interfaces constants are kept as fixed values until")
    lines.append(" * an official ietf-interfaces SID file is added under sid/.")
    lines.append(" */")
    lines.append("")
    lines.append("#ifndef SIDS_H")
    lines.append("#define SIDS_H")
    lines.append("")
    lines.append("/* module: ietf-interfaces (RFC 8343) */")
    lines.append("#define SID_IETF_INTERFACES_MODULE          1500")
    lines.append("#define SID_IF_INTERFACE                    1533")
    lines.append("#define SID_IF_DESCRIPTION                  1534")
    lines.append("#define SID_IF_ENABLED                      1535")
    lines.append("#define SID_IF_NAME                         1537")
    lines.append("#define SID_IF_TYPE                         1538")
    lines.append("#define SID_IF_OPER_STATUS                  1544")
    lines.append("#define SID_IF_IDENTITY_ETHERNET_CSMACD    1880")
    lines.append("")
    lines.append("#define DELTA_IF_DESCRIPTION    (SID_IF_DESCRIPTION  - SID_IF_INTERFACE)")
    lines.append("#define DELTA_IF_ENABLED        (SID_IF_ENABLED      - SID_IF_INTERFACE)")
    lines.append("#define DELTA_IF_NAME           (SID_IF_NAME         - SID_IF_INTERFACE)")
    lines.append("#define DELTA_IF_TYPE           (SID_IF_TYPE         - SID_IF_INTERFACE)")
    lines.append("#define DELTA_IF_OPER_STATUS    (SID_IF_OPER_STATUS  - SID_IF_INTERFACE)")
    lines.append("")
    lines.append("/* module: ietf-system (RFC 7317) — from sid/ietf-system.sid */")
    lines.append(f"#define SID_IETF_SYSTEM_MODULE              {sid_sys_module}")
    lines.append(f"#define SID_SYS_CLOCK                       {sid_sys_clock}")
    lines.append(f"#define SID_SYS_CLOCK_BOOT_DATETIME         {sid_sys_clock_boot}")
    lines.append(f"#define SID_SYS_CLOCK_CURRENT_DATETIME      {sid_sys_clock_current}")
    lines.append(f"#define SID_SYS_NTP_ENABLED                 {sid_sys_ntp_enabled}")
    lines.append(f"#define SID_SYS_NTP_SERVER                  {sid_sys_ntp_server}")
    lines.append(f"#define SID_SYS_NTP_SERVER_NAME             {sid_sys_ntp_server_name}")
    lines.append(f"#define SID_SYS_NTP_SERVER_PREFER           {sid_sys_ntp_server_prefer}")
    lines.append(f"#define SID_SYS_NTP_SERVER_UDP              {sid_sys_ntp_server_udp}")
    lines.append(f"#define SID_SYS_NTP_SERVER_UDP_ADDRESS      {sid_sys_ntp_server_udp_address}")
    lines.append("")
    lines.append("#define DELTA_CLOCK_BOOT_DATETIME    (SID_SYS_CLOCK_BOOT_DATETIME    - SID_SYS_CLOCK)")
    lines.append("#define DELTA_CLOCK_CURRENT_DATETIME (SID_SYS_CLOCK_CURRENT_DATETIME - SID_SYS_CLOCK)")
    lines.append("")
    lines.append("#define DELTA_NTP_SERVER_NAME    (SID_SYS_NTP_SERVER_NAME    - SID_SYS_NTP_SERVER)")
    lines.append("#define DELTA_NTP_SERVER_PREFER  (SID_SYS_NTP_SERVER_PREFER  - SID_SYS_NTP_SERVER)")
    lines.append("#define DELTA_NTP_SERVER_UDP     (SID_SYS_NTP_SERVER_UDP     - SID_SYS_NTP_SERVER)")
    lines.append("#define DELTA_NTP_UDP_ADDRESS    (SID_SYS_NTP_SERVER_UDP_ADDRESS - SID_SYS_NTP_SERVER_UDP)")
    lines.append("")
    lines.append("#endif /* SIDS_H */")
    lines.append("")

    return "\n".join(lines)


def main() -> None:
    content = generate()
    OUT_H.write_text(content, encoding="utf-8")
    print(f"Generated {OUT_H.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
